### ISSUE TITLE
Finish up `'tick`/`'static` persistence semantics

### ISSUE THREAD

**Issue by jhellerstein** [hydro-project/hydroflow#364]
- [x] Implement `'static` for `fold` and `reduce` #368
- [x] Replay for `'static` for correctness #377
- [ ] Reevaluate side-effecting operators (e.g. chat doesn't want to reprint every tick) and efficiency (e.g. kvs) (related #380)
- [x] Don't allow generic params such as `'static` on operators that dont handle them (currently silently ignores it) #367

**Comment by MingweiSamuel** [comment]
* Don't allow generic params such as `'static` on operators that dont handle them

**Comment by MingweiSamuel** [comment]
Also need to consider what to do with `difference` persistence if anything

**Comment by MingweiSamuel** [comment]
I'll take a quick look at this to close it

**Comment by MingweiSamuel** [comment]
Seems like this is done, #380, no issues with chat
